// <auto-generated />
namespace HedgefundMe.com.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class introduceNewObjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(introduceNewObjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201408082238461_introduceNewObjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
