// <auto-generated />
namespace HedgefundMe.com.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addPortfolioEntries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPortfolioEntries));
        
        string IMigrationMetadata.Id
        {
            get { return "201409021911233_addPortfolioEntries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
