// <auto-generated />
namespace HedgefundMe.com.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tradesettingsNotStaticField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tradesettingsNotStaticField));
        
        string IMigrationMetadata.Id
        {
            get { return "201408230011354_tradesettingsNotStaticField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
